#include "stdafx.h"

#include "../Entry/Spawn/SpawnPoint.h"
#include "../Entry/WayPoint/WayPoint.h"
#include "../Entry/Folder/FolderObject.h"
#include "../Entry/Shape/EShape.h"
#include "../../../../xrEngine/LevelGameDef.h"
#include "../../../../xrEngine/xrISEAbstract.h"
#include "../../../../xrServerEntities/xrServer_Object_Base.h"
#include "../../../../xrServerEntities/xrMessages.h"

// SceneImport — read the compiled per-level binary files (level.spawn,
// level.game) and drop their contents into the currently-loaded scene as
// fresh editable objects, organised under a timestamped folder.
//
// Both routines reuse the existing engine decoders (CSE_Abstract::Spawn_Read
// for entities, the WAYOBJECT_CHUNK_POINTS/LINKS layout for patrols) rather
// than reimplementing the packet format.
//
// Dedup philosophy — every named entity in the SDK is assumed to have a
// globally-unique name (that's how the editor generates them), so name match
// alone catches accidental re-imports. The one exception is graph_point,
// which the compiler auto-numbers and whose real identity is the (type, xyz)
// pair — two graph_points at the same position are the same node — so we
// coord-dedup those against existing graph_points only.

namespace
{
// Radius for graph_point coord-dedup. Chosen wide enough to catch small
// export-side snapping variance but tight enough to leave hand-placed
// neighbours untouched.
static constexpr float GRAPH_POINT_RADIUS_SQR = 0.5f * 0.5f;

// Sections whose entities are auto-generated by the level compiler from
// geometry markers rather than placed via the editor. Importing them back
// bloats the scene tree with unusable clutter (typical names look like
// "meshes\brkbl#12.ogf") so we drop them at the packet-header stage before
// the CSE_* is even instantiated.
static bool is_excluded_section(LPCSTR section)
{
    if (!section)
        return false;
    static const char* kExcluded[] = {
        "breakable_object",
        "climable_object",
    };
    for (const char* ex: kExcluded)
        if (0 == strcmp(section, ex))
            return true;
    return false;
}

// Windows local time → "Imported DD/MM/YY HH:MM"
static void make_folder_name(char* out, size_t out_sz)
{
    SYSTEMTIME lt;
    ::GetLocalTime(&lt);
    xr_sprintf(out, out_sz, "Imported %02u/%02u/%02u %02u:%02u", lt.wDay, lt.wMonth, lt.wYear % 100, lt.wHour, lt.wMinute);
}

// Get-or-create a timestamped folder for the given class. Kept lazy so a
// run that imports nothing doesn't leave an empty folder behind.
static CFolderObject* ensure_folder(ObjClassID cls, CFolderObject*& cache)
{
    if (cache)
        return cache;
    char base[128];
    make_folder_name(base, sizeof(base));
    string256 unique;
    Scene->GenObjectName(OBJCLASS_FOLDER, unique, base);
    cache = xr_new<CFolderObject>((LPVOID)0, unique);
    cache->SetFolderClass(cls);
    Scene->AppendObject(cache, false);
    return cache;
}

// An existing graph_point spawn point within GRAPH_POINT_RADIUS of pos, or
// null. Only graph_points participate in coord dedup — every other entity
// class relies on unique-name convention.
static CCustomObject* find_matching_graph_point(const Fvector& pos)
{
    ObjectList& lst = Scene->ListObj(OBJCLASS_SPAWNPOINT);
    for (auto* obj: lst)
    {
        CSpawnPoint* sp = dynamic_cast<CSpawnPoint*>(obj);
        if (!sp || sp->IsDeleted() || !sp->m_SpawnData.Valid())
            continue;
        LPCSTR existing_section = sp->m_SpawnData.m_Data->name();
        if (!existing_section || 0 != strcmp(existing_section, "graph_point"))
            continue;
        const Fvector& p  = sp->GetPosition();
        float          dx = p.x - pos.x, dy = p.y - pos.y, dz = p.z - pos.z;
        if (dx * dx + dy * dy + dz * dz <= GRAPH_POINT_RADIUS_SQR)
            return sp;
    }
    return nullptr;
}
}   // namespace

bool EScene::ImportLevelSpawn(LPCSTR path, ImportStats& stats)
{
    IReader* R = FS.r_open(path);
    if (!R)
    {
        ELog.DlgMsg(mtError, "! Import: can't open '%s'", path);
        return false;
    }

    Msg("- Import: reading level.spawn '%s'", path);

    CFolderObject* folder = nullptr;
    u32            chunk_iter;
    IReader*       chunk = R->open_chunk_iterator(chunk_iter);
    for (; chunk; chunk = R->open_chunk_iterator(chunk_iter, chunk))
    {
        NET_Packet packet;
        packet.B.count = chunk->length();
        if (packet.B.count == 0 || packet.B.count >= NET_PacketSizeLimit)
        {
            Msg("! Import: entity chunk size %u is out of range", packet.B.count);
            stats.errors++;
            continue;
        }
        chunk->r(packet.B.data, packet.B.count);

        // Peek: u16 M_SPAWN | stringZ section | stringZ entity_name | ...
        // Spawn_Read below re-invokes r_begin so the read cursor left here
        // is irrelevant to the subsequent full parse.
        u16 tag;
        packet.r_begin(tag);
        if (tag != M_SPAWN)
        {
            Msg("! Import: chunk tag 0x%04x != M_SPAWN, skipped", tag);
            stats.errors++;
            continue;
        }
        string64 section;
        packet.r_stringZ(section);

        // Compiler-generated clutter — drop before spending any work on it.
        if (is_excluded_section(section))
        {
            string4096 name_peek = {0};
            packet.r_stringZ(name_peek);
            Msg("- Import skip: '%s' - excluded section '%s'", name_peek, section);
            stats.skipped_excluded++;
            continue;
        }

        CSpawnPoint* sp = xr_new<CSpawnPoint>((LPVOID)0, "");
        if (!sp->CreateSpawnData(section))
        {
            Msg("- Import skip: entity section '%s' unknown in current game configs", section);
            xr_delete(sp);
            stats.errors++;
            continue;
        }

        if (!sp->m_SpawnData.m_Data->Spawn_Read(packet))
        {
            Msg("- Import skip: Spawn_Read failed for section '%s'", section);
            xr_delete(sp);
            stats.errors++;
            continue;
        }

        LPCSTR         entity_name = sp->m_SpawnData.m_Data->name_replace();
        const Fvector& pos         = sp->m_SpawnData.m_Data->position();
        const Fvector& ang         = sp->m_SpawnData.m_Data->angle();
        sp->SetName(entity_name);
        // Set{Position,Rotation} are re-declared protected on CSpawnPoint;
        // call through the CCustomObject base where they are public.
        static_cast<CCustomObject*>(sp)->SetPosition(pos);
        static_cast<CCustomObject*>(sp)->SetRotation(ang);

        // Shape-bearing entities (space_restrictor, level_changer, smart_terrain,
        // campfire, torrid_zone, ...) carry their cform inside the packet.
        // Spawn_Read populated m_Data->shape()->shapes; we mirror that into a
        // CEditShape and attach it so the volume is visible in the editor.
        // Without this the spawn point would show only as a point marker,
        // which is what the user reported as "missing associated shapes".
        ISE_Shape* cform = sp->m_SpawnData.m_Data->shape();
        if (cform && !cform->shapes.empty())
        {
            string64 shape_name;
            GenObjectName(OBJCLASS_SHAPE, shape_name, "shape");
            CEditShape* eshape = xr_new<CEditShape>((LPVOID)0, shape_name);
            for (const CShapeData::shape_def& s: cform->shapes)
            {
                if (s.type == CShapeData::cfSphere)
                    eshape->add_sphere(s.data.sphere);
                else if (s.type == CShapeData::cfBox)
                    eshape->add_box(s.data.box);
            }
            // Position/rotation on the shape must match the entity because
            // CSpawnPoint::AttachObject copies transform FROM shape TO the
            // spawn point (not the other way around).
            eshape->SetPosition(pos);
            eshape->SetRotation(ang);
            AppendObject(eshape, false);
            sp->AttachObject(eshape);
        }

        // Name dedup — the universal duplicate check.
        if (FindObjectByName(entity_name, OBJCLASS_SPAWNPOINT))
        {
            Msg("- Import skip: '%s' at (%.2f, %.2f, %.2f) - duplicate name", entity_name, pos.x, pos.y, pos.z);
            xr_delete(sp);
            stats.skipped_name++;
            continue;
        }

        // Coord dedup — graph_point only, because that's the only entity
        // class whose identity is inherently positional.
        if (0 == strcmp(section, "graph_point"))
        {
            if (CCustomObject* near_obj = find_matching_graph_point(pos))
            {
                Msg("- Import skip: '%s' at (%.2f, %.2f, %.2f) - overlapping graph_point '%s'", entity_name, pos.x, pos.y, pos.z, near_obj->GetName());
                xr_delete(sp);
                stats.skipped_coord++;
                continue;
            }
        }

        ensure_folder(OBJCLASS_SPAWNPOINT, folder);
        AppendObject(sp, false);
        folder->AddChild(sp);
        stats.imported++;
    }

    FS.r_close(R);
    Msg("- Import: level.spawn done — imported=%d skipped_name=%d skipped_coord=%d skipped_excluded=%d errors=%d",
        stats.imported, stats.skipped_name, stats.skipped_coord, stats.skipped_excluded, stats.errors);
    return true;
}

bool EScene::ImportLevelGame(LPCSTR path, ImportStats& stats)
{
    IReader* R = FS.r_open(path);
    if (!R)
    {
        ELog.DlgMsg(mtError, "! Import: can't open '%s'", path);
        return false;
    }

    IReader* patrols = R->open_chunk(WAY_PATROLPATH_CHUNK);
    if (!patrols)
    {
        ELog.DlgMsg(mtError, "! Import: no WAY_PATROLPATH_CHUNK in '%s' (is this a level.game file?)", path);
        FS.r_close(R);
        return false;
    }

    Msg("- Import: reading level.game '%s'", path);

    CFolderObject* folder = nullptr;
    u32            sub_iter;
    IReader*       sub = patrols->open_chunk_iterator(sub_iter);
    for (; sub; sub = patrols->open_chunk_iterator(sub_iter, sub))
    {
        if (!sub->find_chunk(WAYOBJECT_CHUNK_VERSION))
        {
            stats.errors++;
            continue;
        }
        u16 version = sub->r_u16();
        if (version != WAYOBJECT_VERSION)
        {
            Msg("- Import skip: patrol version %u != %u", version, WAYOBJECT_VERSION);
            stats.errors++;
            continue;
        }

        if (!sub->find_chunk(WAYOBJECT_CHUNK_NAME))
        {
            stats.errors++;
            continue;
        }
        shared_str patrol_name;
        sub->r_stringZ(patrol_name);

        // Name-only dedup for patrols — a patrol's identity is its name.
        // Coord matching doesn't apply because two independent patrols may
        // legitimately start at very similar positions (e.g. _walk / _look
        // twin pairs) and we'd wrongly reject the second one.
        if (FindObjectByName(patrol_name.c_str(), OBJCLASS_WAY))
        {
            Msg("- Import skip: patrol '%s' - duplicate name", patrol_name.c_str());
            stats.skipped_name++;
            continue;
        }

        CWayObject* w = xr_new<CWayObject>((LPVOID)0, patrol_name.c_str());
        if (!w->LoadFromLevelGame(*sub))
        {
            Msg("- Import skip: patrol '%s' has malformed points/links", patrol_name.c_str());
            xr_delete(w);
            stats.errors++;
            continue;
        }

        ensure_folder(OBJCLASS_WAY, folder);
        AppendObject(w, false);
        folder->AddChild(w);
        stats.imported++;
    }

    patrols->close();
    FS.r_close(R);
    Msg("- Import: level.game done — imported=%d skipped_name=%d errors=%d", stats.imported, stats.skipped_name, stats.errors);
    return true;
}
