#include "stdafx.h"

#include "../Entry/Spawn/SpawnPoint.h"
#include "../Entry/WayPoint/WayPoint.h"
#include "../Entry/Folder/FolderObject.h"
#include "../Entry/Shape/EShape.h"
#include "../../../../xrEngine/LevelGameDef.h"
#include "../../../../xrEngine/xrISEAbstract.h"
#include "../../../../xrEngine/xrISEALifeObject.h"
#include "../../../../xrServerEntities/xrServer_Object_Base.h"
#include "../../../../xrServerEntities/xrMessages.h"

// SceneImport — read the compiled binary spawn / game files (level.spawn,
// level.game, all.spawn) and drop their contents into the currently-loaded
// scene as fresh editable objects, organised under a timestamped folder.
//
// Both routines reuse the existing engine decoders (CSE_Abstract::Spawn_Read
// for entities, our CWayObject::LoadFromLevelGame / LoadFromAllSpawn for
// patrols) rather than reimplementing the packet format.
//
// Dedup philosophy — every named entity in the SDK is assumed to have a
// globally-unique name (that's how the editor generates them), so name match
// alone catches accidental re-imports. The one exception is graph_point,
// which the compiler auto-numbers and whose real identity is the (type, xyz)
// pair — two graph_points at the same position are the same node — so we
// coord-dedup those against existing graph_points only.
//
// all.spawn variants add a level filter driven by the file's game graph
// (chunk 4). The graph maps game_vertex_id → level_id → level name; entities
// whose graph vertex resolves to a level other than the currently-loaded one
// are skipped (skipped_wrong_level).

namespace
{
// Radius for graph_point coord-dedup. Chosen wide enough to catch small
// export-side snapping variance but tight enough to leave hand-placed
// neighbours untouched.
static constexpr float GRAPH_POINT_RADIUS_SQR = 0.5f * 0.5f;

// Sections we drop before instantiating the CSE_*, for two distinct reasons:
//
//   breakable_object / climable_object — auto-generated by the level compiler
//   from geometry markers rather than placed via the editor. Importing them
//   back bloats the scene tree with unusable clutter (typical names look like
//   "meshes\brkbl#12.ogf").
//
//   smart_cover — the editor's Lua env doesn't ship every mod-specific
//   smart_covers.descriptions entry, so Spawn_Read → STATE_Read invokes
//   se_smart_cover.script which fatal-asserts through the Lua guard when a
//   description isn't registered. Skipping at the packet-header stage keeps
//   the import running; smart_covers must be authored directly in the editor.
static bool is_excluded_section(LPCSTR section)
{
    if (!section)
        return false;
    static const char* kExcluded[] = {
        "breakable_object",
        "climable_object",
        "smart_cover",
    };
    for (const char* ex: kExcluded)
        if (0 == strcmp(section, ex))
            return true;
    return false;
}

// Windows local time → "Imported DD/MM/YY HH:MM"
static void make_folder_name(char* out, size_t out_sz)
{
    SYSTEMTIME lt;
    ::GetLocalTime(&lt);
    xr_sprintf(out, out_sz, "Imported %02u/%02u/%02u %02u:%02u", lt.wDay, lt.wMonth, lt.wYear % 100, lt.wHour, lt.wMinute);
}

// Get-or-create a timestamped folder for the given class. Kept lazy so a
// run that imports nothing doesn't leave an empty folder behind.
static CFolderObject* ensure_folder(ObjClassID cls, CFolderObject*& cache)
{
    if (cache)
        return cache;
    char base[128];
    make_folder_name(base, sizeof(base));
    string256 unique;
    Scene->GenObjectName(OBJCLASS_FOLDER, unique, base);
    cache = xr_new<CFolderObject>((LPVOID)0, unique);
    cache->SetFolderClass(cls);
    Scene->AppendObject(cache, false);
    return cache;
}

// An existing graph_point spawn point within GRAPH_POINT_RADIUS of pos, or
// null. Only graph_points participate in coord dedup — every other entity
// class relies on unique-name convention.
static CCustomObject* find_matching_graph_point(const Fvector& pos)
{
    ObjectList& lst = Scene->ListObj(OBJCLASS_SPAWNPOINT);
    for (auto* obj: lst)
    {
        CSpawnPoint* sp = dynamic_cast<CSpawnPoint*>(obj);
        if (!sp || sp->IsDeleted() || !sp->m_SpawnData.Valid())
            continue;
        LPCSTR existing_section = sp->m_SpawnData.m_Data->name();
        if (!existing_section || 0 != strcmp(existing_section, "graph_point"))
            continue;
        const Fvector& p  = sp->GetPosition();
        float          dx = p.x - pos.x, dy = p.y - pos.y, dz = p.z - pos.z;
        if (dx * dx + dy * dy + dz * dz <= GRAPH_POINT_RADIUS_SQR)
            return sp;
    }
    return nullptr;
}

// ---------------------------------------------------------------------------
// GameGraphLevelMap — parses all.spawn chunk 4 (the compiled game graph) into
// a vertex_id → level_name lookup. Only the level table and the packed
// (level_id:8 | level_vertex_id:24) word at byte 24 of each 42-byte vertex
// record are read; everything else in the graph is ignored.
//
// See `compiler/parsers/game_graph.py` in the LAMBDA tools for the reference
// implementation of the on-disk format.
// ---------------------------------------------------------------------------
class GameGraphLevelMap
{
public:
    GameGraphLevelMap(): m_valid(false), m_vertex_count(0) {}

    // Populate from an already-opened chunk 4. Returns false if the header
    // looks malformed. Versions 8, 9 and 10 all share the vertex layout
    // (see `game_graph_space.h::CVertex` — 42 bytes, packed level word at
    // offset 24). Newer values still get read but warned.
    bool load(IReader& F)
    {
        u8  version           = F.r_u8();
        u16 vertex_count      = F.r_u16();
        u32 edge_count        = F.r_u32();
        (void)edge_count;
        u32 death_point_count = F.r_u32();
        (void)death_point_count;
        F.advance(16);   // xrGUID
        u8 level_count = F.r_u8();

        if (version < 8 || version > 10)
            Msg("! Import: unfamiliar game graph version %u — attempting to read anyway", (u32)version);

        // Per-level record: stringZ name, Fvector offset, u8 level_id,
        // stringZ section, xrGUID.
        shared_str name_buf;
        shared_str section_buf;
        for (u8 i = 0; i < level_count; ++i)
        {
            F.r_stringZ(name_buf);
            F.advance(12);   // Fvector offset — unused
            u8 level_id = F.r_u8();
            F.r_stringZ(section_buf);
            F.advance(16);   // xrGUID

            m_level_by_id[level_id] = name_buf;
        }

        m_vertex_count = vertex_count;
        // Vertex records are exactly 42 bytes and contain the packed level word
        // at offset 24. We stream them here so a later find_level() is a plain
        // map lookup.
        for (u32 v = 0; v < vertex_count; ++v)
        {
            F.advance(24);           // local + global Fvector = 2 * 12 = 24
            u32 packed = F.r_u32();
            F.advance(42 - 24 - 4);   // 4 vertex_types + 4 edge_off + 4 dp_off + 1 nc + 1 dpc = 14
            u32 level_id = packed & 0xFFu;
            m_level_by_vertex[v] = (u8)level_id;
        }

        m_valid = true;
        return true;
    }

    // Log a level_id → name → vertex_count breakdown. Diagnostic. Runs
    // O(levels * vertices) but this is called once per import and levels ≤ 30,
    // vertices ≤ ~100k, so the cost is negligible.
    void log_summary() const
    {
        Msg("- Import: game graph has %u levels, %u vertices", (u32)m_level_by_id.size(), (u32)m_vertex_count);
        for (auto& kv: m_level_by_id)
        {
            u32 count = 0;
            for (auto& vk: m_level_by_vertex)
                if (vk.second == kv.first)
                    ++count;
            Msg("- Import:   level_id=%u name='%s' vertex_count=%u", (u32)kv.first, kv.second.c_str(), count);
        }
    }

    bool valid() const { return m_valid; }

    // Vertex count for a specific level name. Zero means "level table has an
    // entry for this name but no vertices point at it" — a stub level, e.g.
    // reserved for a mod that never filled it in. Callers can use this to
    // distinguish "wrong file" from "level exists but is empty".
    u32 vertex_count_for_level(LPCSTR name) const
    {
        if (!name || !*name)
            return 0;
        u8 target_id = 0xFF;
        for (auto& kv: m_level_by_id)
            if (0 == xr_strcmp(kv.second.c_str(), name))
            {
                target_id = kv.first;
                break;
            }
        if (target_id == 0xFF)
            return 0;
        u32 count = 0;
        for (auto& kv: m_level_by_vertex)
            if (kv.second == target_id)
                ++count;
        return count;
    }

    // Look up the level name for the given game vertex id. False if the id
    // isn't in the graph.
    bool find_level(u32 vertex_id, shared_str& out) const
    {
        auto it_v = m_level_by_vertex.find(vertex_id);
        if (it_v == m_level_by_vertex.end())
            return false;
        auto it_l = m_level_by_id.find(it_v->second);
        if (it_l == m_level_by_id.end())
            return false;
        out = it_l->second;
        return true;
    }

    // Whether the graph's level table contains the given name (case sensitive
    // — the SDK's m_LevelPrefix is stored as-is and the game graph likewise).
    bool has_level(LPCSTR name) const
    {
        if (!name || !*name)
            return false;
        for (auto& kv: m_level_by_id)
            if (0 == xr_strcmp(kv.second.c_str(), name))
                return true;
        return false;
    }

    // For error messages: build a comma-separated list of the levels present.
    void list_levels(xr_string& out) const
    {
        out.clear();
        for (auto& kv: m_level_by_id)
        {
            if (!out.empty())
                out += ", ";
            out += kv.second.c_str();
        }
    }

private:
    bool                       m_valid;
    u32                        m_vertex_count;
    xr_map<u8, shared_str>     m_level_by_id;
    xr_map<u32, u8>            m_level_by_vertex;
};

// Peek m_tGraphID from a spawn packet without invoking Spawn_Read. Called on
// entry to import_one_spawn_packet after r_begin(tag) + r_stringZ(section) —
// walks the CSE_Abstract header on modern (v >= 112) packets, then reads the
// first two bytes of STATE, which for CSE_ALifeObject-derived classes are the
// game vertex id. Restores the reader position before returning so the caller
// can Spawn_Read the same packet unchanged.
//
// The whole point is to let the level filter run *before* Spawn_Read. STATE_Read
// for some Anomaly-side classes (e.g. smart_cover via se_smart_cover.script)
// calls Lua that isn't fully registered in the editor's script env and fatal-
// asserts. Wrong-level packets that we can filter here never touch those paths.
//
// Returns false for graph_point (CSE_Abstract-derived, so STATE doesn't start
// with m_tGraphID), for pre-v112 packets, or for any truncated packet. Callers
// fall back to the post-Spawn_Read filter in those cases.
static bool peek_alife_graph_id(NET_Packet& packet, LPCSTR section, u16& out_gvid)
{
    if (section && 0 == strcmp(section, "graph_point"))
        return false;

    struct restore_pos
    {
        NET_Packet& p;
        u32         saved;
        restore_pos(NET_Packet& q): p(q), saved(q.r_pos) {}
        ~restore_pos() { p.r_pos = saved; }
    } guard(packet);

    const u32 buf_size = (u32)packet.B.count;
    const u8* buf      = packet.B.data;

    auto need = [&](u32 n) -> bool { return packet.r_pos + n <= buf_size; };
    auto skip_stringZ = [&]() -> bool {
        while (packet.r_pos < buf_size && buf[packet.r_pos] != 0)
            ++packet.r_pos;
        if (packet.r_pos >= buf_size)
            return false;
        ++packet.r_pos;
        return true;
    };

    // name stringZ
    if (!skip_stringZ())
        return false;

    // gameid u8 + RP u8 + Position vec3 + Angle vec3 + RespawnTime u16 +
    // ID u16 + ID_Parent u16 + ID_Phantom u16 = 34 bytes
    if (!need(1 + 1 + 12 + 12 + 2 + 2 + 2 + 2))
        return false;
    packet.r_pos += 1 + 1 + 12 + 12 + 2 + 2 + 2 + 2;

    if (!need(2))
        return false;
    u16 s_flags = *reinterpret_cast<const u16*>(buf + packet.r_pos);
    packet.r_pos += 2;

    u16 wVersion = 0;
    if (s_flags & M_SPAWN_VERSION)
    {
        if (!need(2))
            return false;
        wVersion = *reinterpret_cast<const u16*>(buf + packet.r_pos);
        packet.r_pos += 2;
    }

    // Modern packet path only — legacy (< 112) has spawn-control fields and
    // an older STATE layout we don't decode here.
    if (wVersion < 112)
        return false;

    // game_type u16 (v > 120)
    if (wVersion > 120)
    {
        if (!need(2))
            return false;
        packet.r_pos += 2;
    }

    // script_version u16 (v > 69, always true here)
    if (!need(2))
        return false;
    packet.r_pos += 2;

    // client_data: u16 size prefix (v > 93) or u8 (older), then the blob
    u32 client_data_size = 0;
    if (wVersion > 93)
    {
        if (!need(2))
            return false;
        client_data_size = *reinterpret_cast<const u16*>(buf + packet.r_pos);
        packet.r_pos += 2;
    }
    else
    {
        if (!need(1))
            return false;
        client_data_size = buf[packet.r_pos];
        packet.r_pos += 1;
    }
    if (!need(client_data_size))
        return false;
    packet.r_pos += client_data_size;

    // m_tSpawnID u16 (always true for v >= 112)
    if (!need(2))
        return false;
    packet.r_pos += 2;

    // state size u16, then STATE begins
    if (!need(2))
        return false;
    packet.r_pos += 2;

    // For CSE_ALifeObject-derived classes at wVersion >= 83, STATE opens with
    // m_tGraphID as u16. Non-ALife derivatives (only graph_point in practice)
    // are excluded above.
    if (!need(2))
        return false;
    out_gvid = *reinterpret_cast<const u16*>(buf + packet.r_pos);
    return true;
}

// ---------------------------------------------------------------------------
// Per-packet spawn-import body — shared between the level.spawn and all.spawn
// paths. On entry `packet` is a NET_Packet whose B.data / B.count hold a raw
// M_SPAWN blob; that's exactly what CSE_Abstract::Spawn_Read expects.
//
// gmap + filter_level are non-null only for the all.spawn path; when set,
// entities whose m_tGraphID doesn't resolve to filter_level are dropped.
// ---------------------------------------------------------------------------
static void import_one_spawn_packet(
    NET_Packet& packet, CFolderObject*& folder,
    const GameGraphLevelMap* gmap, LPCSTR filter_level,
    EScene::ImportStats& stats)
{
    u16 tag;
    packet.r_begin(tag);
    if (tag != M_SPAWN)
    {
        Msg("! Import: chunk tag 0x%04x != M_SPAWN, skipped", tag);
        stats.errors++;
        return;
    }
    string64 section;
    packet.r_stringZ(section);

    // Compiler-generated clutter — drop before spending any work on it.
    if (is_excluded_section(section))
    {
        string4096 name_peek = {0};
        packet.r_stringZ(name_peek);
        Msg("- Import skip: '%s' - excluded section '%s'", name_peek, section);
        stats.skipped_excluded++;
        return;
    }

    // Pre-Spawn_Read level filter. STATE_Read for smart_cover (and any other
    // Anomaly-side class whose Lua bindings aren't fully registered in the
    // editor) fatal-asserts on a Lua guard, taking the whole import down. Peek
    // m_tGraphID from the packet header so wrong-level packets never reach
    // Spawn_Read. Entities the peek can't classify (graph_point, pre-v112
    // formats) fall through to the post-Spawn_Read filter below.
    if (gmap && filter_level && *filter_level)
    {
        u16 peek_gvid = 0;
        if (peek_alife_graph_id(packet, section, peek_gvid))
        {
            shared_str resolved;
            if (gmap->find_level((u32)peek_gvid, resolved))
            {
                if (0 != xr_strcmp(resolved.c_str(), filter_level))
                {
                    Msg("- Import skip: section '%s' - level '%s' != '%s' (pre-load)",
                        section, resolved.c_str(), filter_level);
                    stats.skipped_wrong_level++;
                    return;
                }
            }
        }
    }

    CSpawnPoint* sp = xr_new<CSpawnPoint>((LPVOID)0, "");
    if (!sp->CreateSpawnData(section))
    {
        Msg("- Import skip: entity section '%s' unknown in current game configs", section);
        xr_delete(sp);
        stats.errors++;
        return;
    }

    if (!sp->m_SpawnData.m_Data->Spawn_Read(packet))
    {
        Msg("- Import skip: Spawn_Read failed for section '%s'", section);
        xr_delete(sp);
        stats.errors++;
        return;
    }

    LPCSTR         entity_name = sp->m_SpawnData.m_Data->name_replace();
    const Fvector& pos         = sp->m_SpawnData.m_Data->position();
    const Fvector& ang         = sp->m_SpawnData.m_Data->angle();

    // Level filter — only meaningful when we have both a graph and a target
    // level. Non-ALife entities lack m_tGraphID entirely; they get imported
    // unconditionally (they're rare enough that the noise is acceptable and
    // the alternative is silently dropping them).
    if (gmap && filter_level && *filter_level)
    {
        ISE_ALifeObject* alife = sp->m_SpawnData.m_Data->CastALifeObject();
        if (alife)
        {
            shared_str resolved;
            if (gmap->find_level((u32)alife->m_tGraphID, resolved))
            {
                if (0 != xr_strcmp(resolved.c_str(), filter_level))
                {
                    Msg("- Import skip: '%s' at (%.2f, %.2f, %.2f) - level '%s' != '%s'",
                        entity_name, pos.x, pos.y, pos.z, resolved.c_str(), filter_level);
                    xr_delete(sp);
                    stats.skipped_wrong_level++;
                    return;
                }
            }
            // If the graph vertex isn't in the map (rare — stale spawn packet
            // pointing at a graph vertex that no longer exists), fall through
            // and let the user see it rather than silently dropping. The name
            // dedup below still catches genuine duplicates.
        }
    }

    sp->SetName(entity_name);
    // Set{Position,Rotation} are re-declared protected on CSpawnPoint;
    // call through the CCustomObject base where they are public.
    static_cast<CCustomObject*>(sp)->SetPosition(pos);
    static_cast<CCustomObject*>(sp)->SetRotation(ang);

    // Shape-bearing entities (space_restrictor, level_changer, smart_terrain,
    // campfire, torrid_zone, ...) carry their cform inside the packet.
    // Spawn_Read populated m_Data->shape()->shapes; we mirror that into a
    // CEditShape and attach it so the volume is visible in the editor.
    ISE_Shape* cform = sp->m_SpawnData.m_Data->shape();
    if (cform && !cform->shapes.empty())
    {
        string64 shape_name;
        Scene->GenObjectName(OBJCLASS_SHAPE, shape_name, "shape");
        CEditShape* eshape = xr_new<CEditShape>((LPVOID)0, shape_name);
        for (const CShapeData::shape_def& s: cform->shapes)
        {
            if (s.type == CShapeData::cfSphere)
                eshape->add_sphere(s.data.sphere);
            else if (s.type == CShapeData::cfBox)
                eshape->add_box(s.data.box);
        }
        // Position/rotation on the shape must match the entity because
        // CSpawnPoint::AttachObject copies transform FROM shape TO the
        // spawn point (not the other way around).
        eshape->SetPosition(pos);
        eshape->SetRotation(ang);
        Scene->AppendObject(eshape, false);
        sp->AttachObject(eshape);
    }

    // Name dedup — the universal duplicate check.
    if (Scene->FindObjectByName(entity_name, OBJCLASS_SPAWNPOINT))
    {
        Msg("- Import skip: '%s' at (%.2f, %.2f, %.2f) - duplicate name", entity_name, pos.x, pos.y, pos.z);
        xr_delete(sp);
        stats.skipped_name++;
        return;
    }

    // Coord dedup — graph_point only, because that's the only entity
    // class whose identity is inherently positional.
    if (0 == strcmp(section, "graph_point"))
    {
        if (CCustomObject* near_obj = find_matching_graph_point(pos))
        {
            Msg("- Import skip: '%s' at (%.2f, %.2f, %.2f) - overlapping graph_point '%s'", entity_name, pos.x, pos.y, pos.z, near_obj->GetName());
            xr_delete(sp);
            stats.skipped_coord++;
            return;
        }
    }

    ensure_folder(OBJCLASS_SPAWNPOINT, folder);
    Scene->AppendObject(sp, false);
    folder->AddChild(sp);
    stats.imported++;
}

// ---------------------------------------------------------------------------
// Per-patrol import body for the all.spawn path. Chunk layout on entry: `sub`
// is one per-patrol chunk (sub-chunk 0 = name stringZ, sub-chunk 1 = CPatrolPath
// data). CWayObject::LoadFromAllSpawn does the format-specific parse; here
// we handle the level filter and the folder/dedup wiring.
// ---------------------------------------------------------------------------
static void import_one_all_spawn_patrol(
    IReader* sub, CFolderObject*& folder,
    const GameGraphLevelMap* gmap, LPCSTR filter_level,
    EScene::ImportStats& stats)
{
    IReader* name_chunk = sub->open_chunk(0);
    if (!name_chunk)
    {
        stats.errors++;
        return;
    }
    shared_str patrol_name;
    name_chunk->r_stringZ(patrol_name);
    name_chunk->close();

    IReader* path_chunk = sub->open_chunk(1);
    if (!path_chunk)
    {
        stats.errors++;
        return;
    }

    // Load once. This gives us the first-point GVID for the level filter, and
    // if it turns out to be the wrong level we throw the CWayObject away.
    // Cheaper than a peek-then-load two-pass — the CPatrolPath allocations are
    // small (typical patrol has 2-8 points).
    CWayObject* w = xr_new<CWayObject>((LPVOID)0, patrol_name.c_str());
    u16 first_gvid = u16(-1);
    if (!w->LoadFromAllSpawn(*path_chunk, &first_gvid))
    {
        Msg("- Import skip: patrol '%s' has malformed points/edges", patrol_name.c_str());
        xr_delete(w);
        path_chunk->close();
        stats.errors++;
        return;
    }
    path_chunk->close();

    // Level filter. GVID of 0 or 0xFFFF is an "unknown/unresolved" sentinel in
    // the game format; without a resolvable location we can't say whether the
    // patrol belongs here, so we skip and count as errors rather than force it
    // through (see plan §"Fallback for unresolvable GVID").
    if (gmap && filter_level && *filter_level)
    {
        if (first_gvid == 0 || first_gvid == u16(-1))
        {
            Msg("- Import skip: patrol '%s' - first point has no valid game_vertex_id", patrol_name.c_str());
            xr_delete(w);
            stats.errors++;
            return;
        }
        shared_str resolved;
        if (!gmap->find_level((u32)first_gvid, resolved))
        {
            Msg("- Import skip: patrol '%s' - game_vertex_id %u not in graph", patrol_name.c_str(), (u32)first_gvid);
            xr_delete(w);
            stats.errors++;
            return;
        }
        if (0 != xr_strcmp(resolved.c_str(), filter_level))
        {
            Msg("- Import skip: patrol '%s' - level '%s' != '%s'", patrol_name.c_str(), resolved.c_str(), filter_level);
            xr_delete(w);
            stats.skipped_wrong_level++;
            return;
        }
    }

    // Name dedup after level check — no point warning "duplicate name" for a
    // patrol we would have rejected anyway.
    if (Scene->FindObjectByName(patrol_name.c_str(), OBJCLASS_WAY))
    {
        Msg("- Import skip: patrol '%s' - duplicate name", patrol_name.c_str());
        xr_delete(w);
        stats.skipped_name++;
        return;
    }

    ensure_folder(OBJCLASS_WAY, folder);
    Scene->AppendObject(w, false);
    folder->AddChild(w);
    stats.imported++;
}

}   // namespace

bool EScene::ImportLevelSpawn(LPCSTR path, ImportStats& stats)
{
    IReader* R = FS.r_open(path);
    if (!R)
    {
        ELog.DlgMsg(mtError, "! Import: can't open '%s'", path);
        return false;
    }

    Msg("- Import: reading level.spawn '%s'", path);

    CFolderObject* folder = nullptr;
    u32            chunk_iter;
    IReader*       chunk = R->open_chunk_iterator(chunk_iter);
    for (; chunk; chunk = R->open_chunk_iterator(chunk_iter, chunk))
    {
        NET_Packet packet;
        packet.B.count = chunk->length();
        if (packet.B.count == 0 || packet.B.count >= NET_PacketSizeLimit)
        {
            Msg("! Import: entity chunk size %u is out of range", packet.B.count);
            stats.errors++;
            continue;
        }
        chunk->r(packet.B.data, packet.B.count);

        import_one_spawn_packet(packet, folder, nullptr, nullptr, stats);
    }

    FS.r_close(R);
    Msg("- Import: level.spawn done — imported=%d skipped_name=%d skipped_coord=%d skipped_excluded=%d errors=%d",
        stats.imported, stats.skipped_name, stats.skipped_coord, stats.skipped_excluded, stats.errors);
    return true;
}

bool EScene::ImportLevelGame(LPCSTR path, ImportStats& stats)
{
    IReader* R = FS.r_open(path);
    if (!R)
    {
        ELog.DlgMsg(mtError, "! Import: can't open '%s'", path);
        return false;
    }

    IReader* patrols = R->open_chunk(WAY_PATROLPATH_CHUNK);
    if (!patrols)
    {
        ELog.DlgMsg(mtError, "! Import: no WAY_PATROLPATH_CHUNK in '%s' (is this a level.game file?)", path);
        FS.r_close(R);
        return false;
    }

    Msg("- Import: reading level.game '%s'", path);

    CFolderObject* folder = nullptr;
    u32            sub_iter;
    IReader*       sub = patrols->open_chunk_iterator(sub_iter);
    for (; sub; sub = patrols->open_chunk_iterator(sub_iter, sub))
    {
        if (!sub->find_chunk(WAYOBJECT_CHUNK_VERSION))
        {
            stats.errors++;
            continue;
        }
        u16 version = sub->r_u16();
        if (version != WAYOBJECT_VERSION)
        {
            Msg("- Import skip: patrol version %u != %u", version, WAYOBJECT_VERSION);
            stats.errors++;
            continue;
        }

        if (!sub->find_chunk(WAYOBJECT_CHUNK_NAME))
        {
            stats.errors++;
            continue;
        }
        shared_str patrol_name;
        sub->r_stringZ(patrol_name);

        // Name-only dedup for patrols — a patrol's identity is its name.
        // Coord matching doesn't apply because two independent patrols may
        // legitimately start at very similar positions (e.g. _walk / _look
        // twin pairs) and we'd wrongly reject the second one.
        if (FindObjectByName(patrol_name.c_str(), OBJCLASS_WAY))
        {
            Msg("- Import skip: patrol '%s' - duplicate name", patrol_name.c_str());
            stats.skipped_name++;
            continue;
        }

        CWayObject* w = xr_new<CWayObject>((LPVOID)0, patrol_name.c_str());
        if (!w->LoadFromLevelGame(*sub))
        {
            Msg("- Import skip: patrol '%s' has malformed points/links", patrol_name.c_str());
            xr_delete(w);
            stats.errors++;
            continue;
        }

        ensure_folder(OBJCLASS_WAY, folder);
        AppendObject(w, false);
        folder->AddChild(w);
        stats.imported++;
    }

    patrols->close();
    FS.r_close(R);
    Msg("- Import: level.game done — imported=%d skipped_name=%d errors=%d", stats.imported, stats.skipped_name, stats.errors);
    return true;
}

bool EScene::ImportAllSpawn(LPCSTR path, LPCSTR level_name, ImportStats& stats)
{
    if (!level_name || !*level_name)
    {
        ELog.DlgMsg(mtError, "! Import: current scene has no level name — set the Level Prefix in Scene Options first.");
        return false;
    }

    IReader* R = FS.r_open(path);
    if (!R)
    {
        ELog.DlgMsg(mtError, "! Import: can't open '%s'", path);
        return false;
    }

    Msg("- Import: reading all.spawn '%s' for level '%s'", path, level_name);

    // Chunk 4 — game graph. Required so we can filter entities by level.
    // (Anomaly compiler uses id 4 per the LAMBDA parsers.)
    GameGraphLevelMap gmap;
    IReader*          graph_chunk = R->open_chunk(4);
    if (!graph_chunk)
    {
        ELog.DlgMsg(mtError, "! Import: '%s' has no game graph chunk (is this an all.spawn?)", path);
        FS.r_close(R);
        return false;
    }
    if (!gmap.load(*graph_chunk))
    {
        graph_chunk->close();
        ELog.DlgMsg(mtError, "! Import: '%s' has a malformed game graph", path);
        FS.r_close(R);
        return false;
    }
    graph_chunk->close();
    gmap.log_summary();

    if (!gmap.has_level(level_name))
    {
        ELog.DlgMsg(mtError,
            "! Import: the scene name prefix '%s' was not found in the all.spawn.",
            level_name);
        FS.r_close(R);
        return false;
    }

    // Chunk 1 — SPAWN_CHUNK_DATA. Contains the spawn graph:
    //   inner chunk 0 = header (spawn name + guid)
    //   inner chunk 1 = vertices data → per-vertex chunks → sub-chunk 1
    //                   (CServerEntityWrapper) → sub-chunk 0 (M_SPAWN packet).
    IReader* spawn_container = R->open_chunk(SPAWN_CHUNK_DATA);
    if (!spawn_container)
    {
        ELog.DlgMsg(mtError, "! Import: '%s' has no SPAWN_CHUNK_DATA (id 1)", path);
        FS.r_close(R);
        return false;
    }
    IReader* vertices_data = spawn_container->open_chunk(1);
    if (!vertices_data)
    {
        spawn_container->close();
        ELog.DlgMsg(mtError, "! Import: '%s' spawn container has no vertices chunk", path);
        FS.r_close(R);
        return false;
    }

    CFolderObject* folder = nullptr;

    // Iterate over each vertex chunk (one per entity).
    u32      v_iter;
    IReader* v_chunk = vertices_data->open_chunk_iterator(v_iter);
    for (; v_chunk; v_chunk = vertices_data->open_chunk_iterator(v_iter, v_chunk))
    {
        // Vertex sub-chunk 1 = CServerEntityWrapper.
        IReader* wrapper = v_chunk->open_chunk(1);
        if (!wrapper)
        {
            stats.errors++;
            continue;
        }

        // Wrapper sub-chunk 0 = a 2-byte payload size followed by the raw
        // M_SPAWN NET_Packet bytes. The size prefix comes from Level::save,
        // not from Spawn_Write itself, and is *inside* the chunk data — the
        // chunk header does NOT skip past it. So we read the u16, verify it
        // against the remaining chunk length, then hand only the packet bytes
        // to Spawn_Read. (Without the skip r_begin would read 0x00c7 or
        // similar as the "tag" and reject every entity.)
        IReader* spawn_packet_chunk = wrapper->open_chunk(0);
        if (!spawn_packet_chunk)
        {
            wrapper->close();
            stats.errors++;
            continue;
        }

        u32 chunk_len = spawn_packet_chunk->length();
        if (chunk_len < 2 + 2)   // size + at least M_SPAWN u16
        {
            Msg("! Import: spawn wrapper chunk too small (%u bytes)", chunk_len);
            spawn_packet_chunk->close();
            wrapper->close();
            stats.errors++;
            continue;
        }
        u16 declared_size = spawn_packet_chunk->r_u16();
        u32 remaining     = chunk_len - 2;
        if (declared_size != remaining)
        {
            // Header inconsistency — either not the format we expect or a
            // corrupted mod tool export. Fall back to trusting the chunk
            // length so we don't drop a whole file over one bad packet.
            Msg("! Import: spawn packet declared size %u != remaining %u — trusting remaining", (u32)declared_size, remaining);
        }

        NET_Packet packet;
        packet.B.count = remaining;
        if (packet.B.count == 0 || packet.B.count >= NET_PacketSizeLimit)
        {
            Msg("! Import: spawn packet size %u out of range", packet.B.count);
            stats.errors++;
        }
        else
        {
            spawn_packet_chunk->r(packet.B.data, packet.B.count);
            import_one_spawn_packet(packet, folder, &gmap, level_name, stats);
        }

        spawn_packet_chunk->close();
        wrapper->close();
    }

    vertices_data->close();
    spawn_container->close();
    FS.r_close(R);
    Msg("- Import: all.spawn done — imported=%d skipped_name=%d skipped_coord=%d skipped_excluded=%d skipped_wrong_level=%d errors=%d",
        stats.imported, stats.skipped_name, stats.skipped_coord, stats.skipped_excluded, stats.skipped_wrong_level, stats.errors);
    return true;
}

bool EScene::ImportAllSpawnPatrols(LPCSTR path, LPCSTR level_name, ImportStats& stats)
{
    if (!level_name || !*level_name)
    {
        ELog.DlgMsg(mtError, "! Import: current scene has no level name — set the Level Prefix in Scene Options first.");
        return false;
    }

    IReader* R = FS.r_open(path);
    if (!R)
    {
        ELog.DlgMsg(mtError, "! Import: can't open '%s'", path);
        return false;
    }

    Msg("- Import: reading all.spawn patrols from '%s' for level '%s'", path, level_name);

    // Chunk 4 — game graph, same as ImportAllSpawn.
    GameGraphLevelMap gmap;
    IReader*          graph_chunk = R->open_chunk(4);
    if (!graph_chunk)
    {
        ELog.DlgMsg(mtError, "! Import: '%s' has no game graph chunk (is this an all.spawn?)", path);
        FS.r_close(R);
        return false;
    }
    if (!gmap.load(*graph_chunk))
    {
        graph_chunk->close();
        ELog.DlgMsg(mtError, "! Import: '%s' has a malformed game graph", path);
        FS.r_close(R);
        return false;
    }
    graph_chunk->close();
    gmap.log_summary();

    if (!gmap.has_level(level_name))
    {
        ELog.DlgMsg(mtError,
            "! Import: the scene name prefix '%s' was not found in the all.spawn.",
            level_name);
        FS.r_close(R);
        return false;
    }

    // Chunk 3 — CPatrolPathStorage. Layout:
    //   inner chunk 0 = u32 patrol_count (ignored — enumeration handles it)
    //   inner chunk 1 = patrols container → per-patrol chunks.
    IReader* patrol_storage = R->open_chunk(3);
    if (!patrol_storage)
    {
        ELog.DlgMsg(mtError, "! Import: '%s' has no patrol path chunk (id 3)", path);
        FS.r_close(R);
        return false;
    }
    IReader* patrols_container = patrol_storage->open_chunk(1);
    if (!patrols_container)
    {
        patrol_storage->close();
        ELog.DlgMsg(mtError, "! Import: '%s' patrol storage has no patrols container", path);
        FS.r_close(R);
        return false;
    }

    CFolderObject* folder = nullptr;

    u32            p_iter;
    IReader*       sub = patrols_container->open_chunk_iterator(p_iter);
    for (; sub; sub = patrols_container->open_chunk_iterator(p_iter, sub))
    {
        import_one_all_spawn_patrol(sub, folder, &gmap, level_name, stats);
    }

    patrols_container->close();
    patrol_storage->close();
    FS.r_close(R);
    Msg("- Import: all.spawn patrols done — imported=%d skipped_name=%d skipped_wrong_level=%d errors=%d",
        stats.imported, stats.skipped_name, stats.skipped_wrong_level, stats.errors);
    return true;
}
